version: '3.8'

services:
  mysql:
    command: [--ssl=0]
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    image: mysql:5.7
    restart: always
    volumes:
      - mysql:/var/lib/mysql

  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        VERSION: ${JAVA_VERSION:-7.4}
      target: ${BACKEND_TARGET:-dev}
    command:
      - "--server.port=${BACKEND_SERVER_PORT:-8080}"
      - "--spring.profiles.active=prod"
      - "--spring.jpa.generate-ddl=true"
      - "--spring.jpa.hibernate.ddl-auto=update"
      - "--spring.datasource.url=jdbc:${DATABASE_URL:-mysql://root:root@mysql:3306}/studentDB?useUnicode=true&characterEncoding=utf8&useSSL=false"
    container_name: backend
    depends_on:
      - mysql
    ports:
      - ${BACKEND_PUBLISHED_PORT:-8000}:8000
    restart: always
    volumes:
      - ./:/app

volumes:
  mysql:
